SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM 
(
    SELECT *
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE "Intact%"
) as I INNER JOIN 
(
    SELECT *
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE "Spayed%" or SEX_UPON_OUTCOME LIKE "Neutered%"
) as O
ON I.ANIMAL_ID = O.ANIMAL_ID
